language: java
sudo: false
dist: trusty

notifications:
  email: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

install:
  - ./gradlew tasks

script:
  - ./gradlew build

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
